import 'package:flutter/material.dart';

class CustomerAppScope extends InheritedWidget {
  const CustomerAppScope({
    super.key,
    required this.languageCode,
    required this.onLanguageChanged,
    required this.themeMode,
    required this.onThemeModeChanged,
    required super.child,
  });

  final String languageCode;
  final Future<void> Function(String languageCode) onLanguageChanged;
  final ThemeMode themeMode;
  final Future<void> Function(ThemeMode themeMode) onThemeModeChanged;

  static CustomerAppScope? maybeOf(BuildContext context) =>
      context.dependOnInheritedWidgetOfExactType<CustomerAppScope>();

  @override
  bool updateShouldNotify(CustomerAppScope oldWidget) =>
      languageCode != oldWidget.languageCode ||
      themeMode != oldWidget.themeMode;
}

extension CustomerLocalizationX on BuildContext {
  CustomerAppScope? get _customerScope => CustomerAppScope.maybeOf(this);

  String get languageCode => _customerScope?.languageCode ?? "en";

  bool get isSwahili => languageCode == "sw";

  Future<void> setLanguageCode(String nextLanguageCode) =>
      _customerScope?.onLanguageChanged(nextLanguageCode) ??
      Future<void>.value();

  ThemeMode get themeMode => _customerScope?.themeMode ?? ThemeMode.system;

  Future<void> setThemeMode(ThemeMode nextThemeMode) =>
      _customerScope?.onThemeModeChanged(nextThemeMode) ?? Future<void>.value();

  String tr(
    String key, {
    Map<String, String> values = const <String, String>{},
  }) {
    final Map<String, String> selected =
        _localizedStrings[languageCode] ?? _localizedStrings["en"]!;
    String text = selected[key] ?? _localizedStrings["en"]![key] ?? key;
    for (final MapEntry<String, String> entry in values.entries) {
      text = text.replaceAll("{${entry.key}}", entry.value);
    }
    return text;
  }
}

const Map<String, Map<String, String>>
_localizedStrings = <String, Map<String, String>>{
  "en": <String, String>{
    "lang.en": "English",
    "lang.sw": "Swahili",
    "nav.home": "Home",
    "nav.apartments": "Apartments",
    "nav.houses": "Houses",
    "nav.cars": "Cars",
    "nav.search": "Search",
    "nav.categories": "Categories",
    "nav.account": "Account",
    "hero.tagline":
        "Find verified houses, vehicles, halls, offices, and other rentable assets around you.",
    "hero.useLocation": "Use my location",
    "hero.chooseArea": "Choose area",
    "hero.browseApartments": "Browse apartments",
    "hero.browseHouses": "Browse houses",
    "hero.browseCars": "Browse cars",
    "hero.language": "Language",
    "banner.title": "Looking for rental assets close to you?",
    "banner.skip": "Skip",
    "heading.categories": "Categories",
    "heading.browseCategories": "Browse categories",
    "feed.nearYou": "Near you",
    "feed.apartments": "Apartments",
    "feed.houses": "Rental houses",
    "feed.cars": "Cars and motorcycles",
    "feed.offices": "Offices and halls",
    "feed.other": "Other listings",
    "search.label": "Search listings",
    "search.empty": "No listings were found.",
    "search.emptyQuery": "No listings matched \"{query}\".",
    "search.searching": "Searching listings...",
    "search.searchingQuery": "Searching for \"{query}\"...",
    "search.resultCount": "{count} listings found",
    "search.resultCountQuery": "{count} listings found for \"{query}\"",
    "search.suggestions": "Suggested listings",
    "search.liveHint": "Results update while you type.",
    "search.suggestionsHint":
        "Tap a suggestion or keep scrolling through results.",
    "search.tryAnother": "Try another word, category, or location.",
    "search.clear": "Clear search",
    "popular.houses.title": "Houses",
    "popular.houses.subtitle": "Standalone homes and family rentals.",
    "popular.apartments.title": "Apartments",
    "popular.apartments.subtitle":
        "Serviced stays, flats, and short-stay homes ready for booking.",
    "popular.cars.title": "Cars",
    "popular.cars.subtitle":
        "Popular vehicle rentals ready for immediate requests.",
    "category.empty": "No listings are available in this category yet.",
    "category.error": "This category could not load right now.",
    "category.titleFallback": "Category",
    "category.browseTitle": "Explore this category",
    "category.browseBody":
        "Fresh public listings, clear photos, and quick request access in one place.",
    "category.related": "More public listings",
    "category.tryOthers":
        "There are no live listings in this category yet, but you can keep browsing other active listings below.",
    "listing.public": "Verified public listing",
    "listing.open": "Open listing",
    "listing.view": "View",
    "listing.expandCover": "Expand photo",
    "listing.hint":
        "Swipe through details, open media fullscreen, and send a quick request when ready.",
    "listing.details": "Listing details",
    "listing.media": "Media",
    "listing.tapExpand": "Tap to expand",
    "listing.tapMediaHint":
        "Tap any photo to open it clearly in fullscreen. Videos start playing automatically.",
    "listing.additionalDetails": "Details",
    "listing.request": "Send request",
    "listing.notFound": "Listing not found",
    "agent.title": "Agent details",
    "agent.phoneHidden":
        "Phone number hidden. Pay to unlock this agent contact.",
    "agent.unlockCta": "Unlock phone number",
    "agent.unlockTitle": "Unlock agent phone",
    "agent.unlockBody":
        "Pay once through ClickPesa to reveal this agent contact on this device.",
    "agent.paymentName": "Full name",
    "agent.paymentPhone": "Phone number",
    "agent.paymentContinue": "Pay and unlock number",
    "agent.paymentCheck": "Check payment now",
    "agent.paymentAmount": "Amount: {amount} {currency}",
    "agent.paymentStarted":
        "Payment request sent. Confirm it on your phone. This screen will unlock the number automatically once ClickPesa confirms payment.",
    "agent.paymentMethod": "Payment method: {method}",
    "agent.paymentPromptTo":
        "Payment prompt sent to {phone}. Enter your mobile money PIN on that phone to finish.",
    "agent.phoneVisible": "Phone number",
    "agent.locationUnknown": "Location not shared yet",
    "agent.verified": "Verified agent",
    "agent.unverified": "Verification pending",
    "help.title": "Help",
    "help.bubble": "Help",
    "help.introTitle": "How Kodimali works",
    "help.introBody":
        "Use Kodimali to browse rental listings, choose a location, open listing details, and contact agents quickly when you are ready.",
    "help.paymentTitle": "Why payment is needed",
    "help.paymentBody":
        "Many people send requests to agents or dalali, so a request can take time before they respond. Paying to unlock the phone number helps you call the agent directly when you need a faster response.",
    "help.paymentHowTitle": "How payment is made",
    "help.paymentHowBody":
        "Open a listing, tap unlock phone number, enter your details, then confirm the mobile money payment prompt on your phone. Once ClickPesa confirms payment, the number appears automatically in the app.",
    "help.platformTitle": "Platform support",
    "help.platformBody":
        "The app is currently supported on Android. iOS support is coming soon. For now, iOS users can use the Kodimali website.",
    "help.supportTitle": "Get more help",
    "help.supportBody":
        "Contact us on WhatsApp or call us directly if you need help using the app or completing a payment.",
    "help.whatsappOne": "WhatsApp 0684684972",
    "help.callOne": "Call 0684684972",
    "help.whatsappTwo": "WhatsApp 0628621737",
    "help.callTwo": "Call 0628621737",
    "help.socialTitle": "Find us online",
    "help.socialBody":
        "You can also find us on Instagram and Facebook for updates and support.",
    "help.instagram": "Instagram @kodimali1",
    "help.facebook": "Facebook Kodimali Tanzania",
    "detail.available": "Available",
    "detail.unavailable": "Not available",
    "detail.included": "Included",
    "detail.notIncluded": "Not included",
    "detail.furnishedYes": "Furnished",
    "detail.furnishedNo": "Not furnished",
    "promotion.titleFallback": "Sponsored update",
    "promotion.label": "Sponsored",
    "request.form": "Request form",
    "request.fullName": "Full name",
    "request.email": "Email address",
    "request.phone": "Phone number / WhatsApp",
    "request.phoneOptional": "Phone number / WhatsApp (optional)",
    "request.checkIn": "Check-in date",
    "request.checkOut": "Check-out date",
    "request.guestCount": "Guests (optional)",
    "request.message": "Message (optional)",
    "request.services": "Services to confirm",
    "request.submit": "Send request",
    "request.submitting": "Sending...",
    "request.nameError": "Enter a valid name.",
    "request.emailError": "Enter a valid email address.",
    "request.phoneError": "Enter a valid phone number.",
    "request.dateError": "Choose valid check-in and check-out dates.",
    "request.successTitle": "Your request was sent to the agent.",
    "request.successBody":
        "The agent will reply by email or phone to confirm availability.",
    "request.reference": "Reference: {reference}",
    "request.backHome": "Back home",
    "location.region": "Region",
    "location.district": "District",
    "location.ward": "Ward",
    "location.area": "Area",
    "location.useThis": "Use this location",
    "location.chooseOptional": "Optional",
    "location.clearDistrict": "Use region only",
    "location.clearWard": "Use district only",
    "location.clearArea": "Use ward only",
    "location.retry": "Retry",
    "location.failed": "We could not load locations right now.",
    "media.autoplay": "Autoplay video",
    "media.tapToPlay": "Tap to play video",
    "media.loading": "Loading media...",
    "farm.highlights": "Farm highlights",
    "farm.water": "Water availability",
    "farm.crops": "Best crops",
    "farm.size": "Land size",
    "apartment.servicesTitle": "Available services",
    "apartment.bookingTitle": "Book this apartment",
    "apartment.bookingBody":
        "Choose your stay dates, leave your email, and select the services you want the agent to confirm.",
    "apartment.service.wifi": "WiFi",
    "apartment.service.food": "Food",
    "apartment.service.transport": "Transport",
    "apartment.service.cleaning": "Cleaning",
    "apartment.service.laundry": "Laundry",
    "account.title": "Your KODIMALI",
    "account.customer": "KODIMALI customer",
    "account.optionalTitle": "Sign in when you want more",
    "account.optionalBody":
        "Browsing and guest requests still work without an account. Sign in to track requests, chat with your assigned agent, and sync saved listings.",
    "account.signIn": "Sign in",
    "account.signOut": "Sign out",
    "account.signedOut": "You have signed out.",
    "account.deleteAction": "Request account deletion",
    "account.deleteTitle": "Delete your account?",
    "account.deleteBody":
        "This sends a deletion request to KODIMALI. Support may retain restricted payment, dispute, fraud-prevention, or legal records where required.",
    "account.deleteReason": "Reason (optional)",
    "account.deleteConfirm": "Send deletion request",
    "account.deleteSubmitted":
        "Your deletion request was sent. Support will verify and process it.",
    "account.create": "Create account",
    "account.createTitle": "Create your customer account",
    "account.signInTitle": "Welcome back",
    "account.guestStillWorks":
        "Your account is optional and does not change public browsing or guest requests.",
    "account.password": "Password",
    "account.passwordError": "Use at least 8 characters.",
    "account.confirmEmail":
        "Check your email to confirm the account, then sign in.",
    "account.haveAccount": "Already registered? Sign in",
    "account.needAccount": "New here? Create an account",
    "settings.title": "Account settings",
    "settings.appearance": "Appearance",
    "settings.profile": "Profile information",
    "settings.save": "Save profile",
    "settings.saved": "Your profile was updated.",
    "theme.system": "System",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "password.forgot": "Forgot password?",
    "password.reset": "Reset password",
    "password.resetSent":
        "Check your email for the secure password-reset link.",
    "password.resetHelp": "Enter a new password for your KODIMALI account.",
    "password.new": "New password",
    "password.change": "Change password",
    "password.changed": "Your password was changed.",
    "password.save": "Save new password",
    "saved.title": "Saved listings",
    "saved.empty": "Tap the heart on a listing to keep it here.",
    "recent.title": "Recently viewed",
    "recent.empty": "Listings you open will appear here.",
    "recent.clear": "Clear",
    "listing.save": "Save listing",
    "listing.unsave": "Remove from saved",
    "listing.share": "Share listing",
    "listing.sharedText": "See this rental on KODIMALI: {title}",
    "requests.my": "My requests",
    "requests.emptyTitle": "No linked requests yet",
    "requests.emptyBody":
        "Send a request while signed in, or link an earlier guest request using its reference.",
    "requests.reference": "Reference",
    "requests.agent": "Agent",
    "requests.assignedAgent": "Assigned agent",
    "requests.track": "Track request",
    "requests.progress": "Request progress",
    "requests.openListing": "Open listing",
    "requests.chatOnlyAssigned":
        "This private chat only connects you with the agent assigned to this request.",
    "requests.claimTitle": "Link an earlier request",
    "requests.claimHelp":
        "Use the reference shown after you sent the guest request.",
    "requests.claimAction": "Link request",
    "requests.claimed": "The request is now linked to your account.",
    "requests.notFound": "This request was not found.",
    "chat.title": "Chat with agent",
    "chat.emptyTitle": "Start the conversation",
    "chat.emptyBody":
        "Ask about availability, price, or the next step. The assigned agent will receive your message.",
    "chat.hint": "Write a message…",
    "chat.unavailable": "Chat is temporarily unavailable. Please try again.",
    "viewing.title": "Viewing appointment",
    "viewing.propose": "Propose a time",
    "viewing.empty": "No viewing time has been proposed yet.",
    "viewing.explainer":
        "Choose a suitable time. Your assigned agent can confirm it or suggest another time.",
    "viewing.note": "Meeting note (optional)",
    "viewing.noteHelp": "For example: meet near the main gate.",
    "viewing.send": "Send proposed time",
    "viewing.futureError": "Choose a future date and time.",
    "viewing.confirm": "Confirm time",
    "viewing.cancel": "Cancel appointment",
    "viewing.cancelConfirm":
        "Are you sure you want to cancel this viewing appointment?",
    "viewing.updated": "The viewing appointment was updated.",
    "review.title": "Review this completed rental",
    "review.prompt": "How was your rental experience?",
    "review.comment": "Comment (optional)",
    "review.submit": "Submit verified review",
    "review.ratingError": "Choose a rating from 1 to 5.",
    "review.completedOnly":
        "Only customers with a completed KODIMALI request can review.",
    "review.thanks": "Thank you for your review",
    "booking.status.new": "Request sent",
    "booking.status.checking_availability": "Checking availability",
    "booking.status.contacted": "Agent contacted you",
    "booking.status.viewing_scheduled": "Viewing scheduled",
    "booking.status.reserved": "Reserved",
    "booking.status.confirmed": "Confirmed",
    "booking.status.completed": "Rental completed",
    "booking.status.cancelled": "Cancelled",
    "booking.status.rejected": "Rejected",
    "booking.status.no_response": "No response",
    "booking.status.agent_delayed": "Agent response delayed",
    "booking.status.proposed": "Awaiting confirmation",
    "booking.status.reschedule_requested": "New time requested",
    "booking.status.no_show": "No show",
  },
  "sw": <String, String>{
    "lang.en": "Kiingereza",
    "lang.sw": "Kiswahili",
    "nav.home": "Nyumbani",
    "nav.apartments": "Apartment",
    "nav.houses": "Nyumba",
    "nav.cars": "Magari",
    "nav.search": "Tafuta",
    "nav.categories": "Makundi",
    "nav.account": "Akaunti",
    "hero.tagline":
        "Pata nyumba, magari, kumbi, ofisi, na mali nyingine za kukodisha kutoka kwa mawakala waliothibitishwa.",
    "hero.useLocation": "Tumia eneo langu",
    "hero.chooseArea": "Chagua eneo",
    "hero.browseApartments": "Angalia apartment",
    "hero.browseHouses": "Angalia nyumba",
    "hero.browseCars": "Angalia magari",
    "hero.language": "Lugha",
    "banner.title": "Unatafuta mali za kukodisha karibu na ulipo?",
    "banner.skip": "Ruka",
    "heading.categories": "Makundi",
    "heading.browseCategories": "Angalia makundi",
    "feed.nearYou": "Karibu na wewe",
    "feed.apartments": "Apartment",
    "feed.houses": "Nyumba za kupangisha",
    "feed.cars": "Magari na pikipiki",
    "feed.offices": "Ofisi na kumbi",
    "feed.other": "Matangazo mengine",
    "search.label": "Tafuta matangazo",
    "search.empty": "Hakuna listings zilizopatikana.",
    "search.emptyQuery": "Hakuna listings zilizolingana na \"{query}\".",
    "search.searching": "Inatafuta listings...",
    "search.searchingQuery": "Inatafuta \"{query}\"...",
    "search.resultCount": "Listings {count} zimepatikana",
    "search.resultCountQuery": "Listings {count} zimepatikana kwa \"{query}\"",
    "search.suggestions": "Mapendekezo ya listings",
    "search.liveHint": "Matokeo yanabadilika unapoandika.",
    "search.suggestionsHint":
        "Gusa pendekezo au endelea kushuka kuona matokeo yote.",
    "search.tryAnother": "Jaribu neno, category, au eneo jingine.",
    "search.clear": "Futa utafutaji",
    "popular.houses.title": "Nyumba",
    "popular.houses.subtitle":
        "Nyumba za familia na upangishaji wa muda mrefu.",
    "popular.apartments.title": "Apartment",
    "popular.apartments.subtitle":
        "Apartment za kukaa, short stay, na serviced stays tayari kwa booking.",
    "popular.cars.title": "Magari",
    "popular.cars.subtitle":
        "Magari ya kukodisha yanayopatikana kwa maombi ya haraka.",
    "category.empty": "Hakuna listings kwenye category hii.",
    "category.error": "Category hii haikupakia kwa sasa.",
    "category.titleFallback": "Category",
    "category.browseTitle": "Chunguza category hii",
    "category.browseBody":
        "Listings za umma, picha zilizo wazi, na kutuma ombi kwa haraka sehemu moja.",
    "category.related": "Listings nyingine za umma",
    "category.tryOthers":
        "Bado hakuna listings hai kwenye category hii, lakini unaweza kuendelea kuona listings nyingine hapa chini.",
    "listing.public": "Tangazo la umma lililothibitishwa",
    "listing.open": "Fungua listing",
    "listing.view": "View",
    "listing.expandCover": "Fungua picha",
    "listing.hint":
        "Tembea kwenye maelezo, fungua picha vizuri, na tuma ombi haraka ukiwa tayari.",
    "listing.details": "Maelezo ya listing",
    "listing.media": "Media",
    "listing.tapExpand": "Bonyeza kufungua",
    "listing.tapMediaHint":
        "Bonyeza picha kuiona vizuri. Video zinaanza kucheza zenyewe.",
    "listing.additionalDetails": "Maelezo",
    "listing.request": "Tuma Ombi",
    "listing.notFound": "Listing haikupatikana",
    "agent.title": "Maelezo ya wakala",
    "agent.phoneHidden":
        "Namba ya simu imefichwa. Lipa ili kuona mawasiliano ya wakala huyu.",
    "agent.unlockCta": "Fungua namba ya simu",
    "agent.unlockTitle": "Fungua simu ya wakala",
    "agent.unlockBody":
        "Lipa mara moja kupitia ClickPesa ili kuona namba ya wakala huyu kwenye kifaa hiki.",
    "agent.paymentName": "Jina kamili",
    "agent.paymentPhone": "Namba ya simu",
    "agent.paymentContinue": "Lipa na fungua namba",
    "agent.paymentCheck": "Angalia hali ya malipo",
    "agent.paymentAmount": "Kiasi: {amount} {currency}",
    "agent.paymentStarted":
        "Ombi la malipo limetumwa. Thibitisha kwenye simu yako. Skrini hii itafungua namba moja kwa moja ClickPesa ikishathibitisha malipo.",
    "agent.paymentMethod": "Njia ya malipo: {method}",
    "agent.paymentPromptTo":
        "Ombi la malipo limetumwa kwenda {phone}. Weka PIN ya huduma ya fedha ya simu kwenye simu hiyo kumalizia.",
    "agent.phoneVisible": "Namba ya simu",
    "agent.locationUnknown": "Eneo bado halijawekwa",
    "agent.verified": "Wakala aliyethibitishwa",
    "agent.unverified": "Uthibitisho bado",
    "help.title": "Msaada",
    "help.bubble": "Msaada",
    "help.introTitle": "Jinsi ya kutumia Kodimali",
    "help.introBody":
        "Tumia Kodimali kuangalia listings za kupangisha, kuchagua eneo, kufungua maelezo ya listing, na kuwasiliana na wakala haraka unapokuwa tayari.",
    "help.paymentTitle": "Kwa nini malipo yanahitajika",
    "help.paymentBody":
        "Watu wengi hutuma maombi kwa agent au dalali, hivyo ombi linaweza kuchukua muda kabla hawajajibu. Kulipia kufungua namba ya simu hukusaidia kumpigia wakala moja kwa moja unapohitaji majibu ya haraka.",
    "help.paymentHowTitle": "Jinsi malipo yanavyofanyika",
    "help.paymentHowBody":
        "Fungua listing, bonyeza kufungua namba ya simu, weka taarifa zako, kisha thibitisha ombi la malipo ya simu litakalofika kwenye namba yako. ClickPesa ikishathibitisha malipo, namba itaonekana moja kwa moja ndani ya app.",
    "help.platformTitle": "Mifumo inayotumika",
    "help.platformBody":
        "Kwa sasa app inatumika kwenye Android. Msaada wa iOS unakuja hivi karibuni. Kwa sasa watumiaji wa iOS wanaweza kutumia tovuti ya Kodimali.",
    "help.supportTitle": "Pata msaada zaidi",
    "help.supportBody":
        "Wasiliana nasi kupitia WhatsApp au piga simu moja kwa moja kama unahitaji msaada wa kutumia app au kukamilisha malipo.",
    "help.whatsappOne": "WhatsApp 0684684972",
    "help.callOne": "Piga 0684684972",
    "help.whatsappTwo": "WhatsApp 0628621737",
    "help.callTwo": "Piga 0628621737",
    "help.socialTitle": "Tupate mtandaoni",
    "help.socialBody":
        "Unaweza pia kutupata kwenye Instagram na Facebook kwa updates na msaada.",
    "help.instagram": "Instagram @kodimali1",
    "help.facebook": "Facebook Kodimali Tanzania",
    "detail.available": "Inapatikana",
    "detail.unavailable": "Haipatikani",
    "detail.included": "Imejumuishwa",
    "detail.notIncluded": "Haijajumuishwa",
    "detail.furnishedYes": "Ina fanicha",
    "detail.furnishedNo": "Haina fanicha",
    "promotion.titleFallback": "Sponsored update",
    "promotion.label": "Sponsored",
    "request.form": "Fomu ya ombi",
    "request.fullName": "Jina kamili",
    "request.email": "Barua pepe",
    "request.phone": "Namba ya simu / WhatsApp",
    "request.phoneOptional": "Namba ya simu / WhatsApp (si lazima)",
    "request.checkIn": "Tarehe ya kuingia",
    "request.checkOut": "Tarehe ya kutoka",
    "request.guestCount": "Idadi ya wageni (si lazima)",
    "request.message": "Ujumbe (si lazima)",
    "request.services": "Huduma za kuthibitisha",
    "request.submit": "Tuma Ombi",
    "request.submitting": "Inatuma...",
    "request.nameError": "Weka jina sahihi.",
    "request.emailError": "Weka barua pepe sahihi.",
    "request.phoneError": "Weka namba sahihi.",
    "request.dateError": "Chagua tarehe sahihi za kuingia na kutoka.",
    "request.successTitle": "Ombi lako limetumwa kwa wakala.",
    "request.successBody":
        "Wakala atakujibu kwa email au simu kuthibitisha upatikanaji.",
    "request.reference": "Reference: {reference}",
    "request.backHome": "Rudi Home",
    "location.region": "Region",
    "location.district": "District",
    "location.ward": "Ward",
    "location.area": "Area",
    "location.useThis": "Tumia eneo hili",
    "location.chooseOptional": "Si lazima",
    "location.clearDistrict": "Tumia region tu",
    "location.clearWard": "Tumia district tu",
    "location.clearArea": "Tumia ward tu",
    "location.retry": "Jaribu tena",
    "location.failed": "Hatukuweza kupakia maeneo kwa sasa.",
    "media.autoplay": "Video ya kujiendesha",
    "media.tapToPlay": "Gusa kucheza video",
    "media.loading": "Inapakia media...",
    "farm.highlights": "Vipengele vya shamba",
    "farm.water": "Upatikanaji wa maji",
    "farm.crops": "Mazao bora",
    "farm.size": "Ukubwa wa ardhi",
    "apartment.servicesTitle": "Huduma zinazopatikana",
    "apartment.bookingTitle": "Book apartment hii",
    "apartment.bookingBody":
        "Chagua tarehe za kukaa, acha email yako, na chagua huduma unazotaka wakala athibitishe.",
    "apartment.service.wifi": "WiFi",
    "apartment.service.food": "Chakula",
    "apartment.service.transport": "Usafiri",
    "apartment.service.cleaning": "Usafi",
    "apartment.service.laundry": "Dobi",
    "account.title": "KODIMALI yako",
    "account.customer": "Mteja wa KODIMALI",
    "account.optionalTitle": "Ingia unapohitaji huduma zaidi",
    "account.optionalBody":
        "Kuangalia listings na kutuma ombi kama mgeni bado kunafanya kazi bila akaunti. Ingia kufuatilia maombi, kuzungumza na wakala wako, na kuhifadhi listings.",
    "account.signIn": "Ingia",
    "account.signOut": "Toka",
    "account.signedOut": "Umetoka kwenye akaunti.",
    "account.deleteAction": "Omba akaunti ifutwe",
    "account.deleteTitle": "Ufute akaunti yako?",
    "account.deleteBody":
        "Hii inatuma ombi la kufuta akaunti kwa KODIMALI. Taarifa chache za malipo, migogoro, kuzuia udanganyifu au sheria zinaweza kuhifadhiwa kwa usalama inapohitajika.",
    "account.deleteReason": "Sababu (si lazima)",
    "account.deleteConfirm": "Tuma ombi la kufuta",
    "account.deleteSubmitted":
        "Ombi lako limetumwa. Timu ya msaada italihakiki na kulishughulikia.",
    "account.create": "Fungua akaunti",
    "account.createTitle": "Fungua akaunti yako ya mteja",
    "account.signInTitle": "Karibu tena",
    "account.guestStillWorks":
        "Akaunti si lazima na haibadilishi kuangalia listings au kutuma ombi kama mgeni.",
    "account.password": "Nenosiri",
    "account.passwordError": "Tumia angalau herufi 8.",
    "account.confirmEmail":
        "Angalia email yako kuthibitisha akaunti, kisha ingia.",
    "account.haveAccount": "Una akaunti tayari? Ingia",
    "account.needAccount": "Ni mara ya kwanza? Fungua akaunti",
    "settings.title": "Mipangilio ya akaunti",
    "settings.appearance": "Mwonekano",
    "settings.profile": "Taarifa za wasifu",
    "settings.save": "Hifadhi wasifu",
    "settings.saved": "Wasifu wako umesasishwa.",
    "theme.system": "Mfumo",
    "theme.light": "Nyeupe",
    "theme.dark": "Giza",
    "password.forgot": "Umesahau nenosiri?",
    "password.reset": "Weka upya nenosiri",
    "password.resetSent":
        "Angalia barua pepe kwa kiungo salama cha kuweka nenosiri upya.",
    "password.resetHelp": "Weka nenosiri jipya la akaunti yako ya KODIMALI.",
    "password.new": "Nenosiri jipya",
    "password.change": "Badilisha nenosiri",
    "password.changed": "Nenosiri lako limebadilishwa.",
    "password.save": "Hifadhi nenosiri jipya",
    "saved.title": "Listings ulizohifadhi",
    "saved.empty": "Bonyeza moyo kwenye listing ili ibaki hapa.",
    "recent.title": "Ulizoangalia hivi karibuni",
    "recent.empty": "Listings utakazofungua zitaonekana hapa.",
    "recent.clear": "Futa",
    "listing.save": "Hifadhi listing",
    "listing.unsave": "Ondoa kwenye zilizohifadhiwa",
    "listing.share": "Shiriki listing",
    "listing.sharedText": "Angalia mali hii KODIMALI: {title}",
    "requests.my": "Maombi yangu",
    "requests.emptyTitle": "Bado hakuna ombi lililounganishwa",
    "requests.emptyBody":
        "Tuma ombi ukiwa umeingia, au unganisha ombi la zamani kwa reference yake.",
    "requests.reference": "Reference",
    "requests.agent": "Wakala",
    "requests.assignedAgent": "Wakala aliyepewa ombi",
    "requests.track": "Fuatilia ombi",
    "requests.progress": "Hatua za ombi",
    "requests.openListing": "Fungua listing",
    "requests.chatOnlyAssigned":
        "Chat hii ya faragha inakuunganisha tu na wakala aliyepewa ombi hili.",
    "requests.claimTitle": "Unganisha ombi la zamani",
    "requests.claimHelp":
        "Tumia reference uliyoonyeshwa baada ya kutuma ombi kama mgeni.",
    "requests.claimAction": "Unganisha ombi",
    "requests.claimed": "Ombi limeunganishwa na akaunti yako.",
    "requests.notFound": "Ombi hili halikupatikana.",
    "chat.title": "Chat na wakala",
    "chat.emptyTitle": "Anza mazungumzo",
    "chat.emptyBody":
        "Uliza kuhusu upatikanaji, bei, au hatua inayofuata. Wakala aliyepewa ombi atapata ujumbe wako.",
    "chat.hint": "Andika ujumbe…",
    "chat.unavailable": "Chat haipatikani kwa sasa. Jaribu tena.",
    "viewing.title": "Miadi ya kuona mali",
    "viewing.propose": "Pendekeza muda",
    "viewing.empty": "Bado hakuna muda wa kuona mali uliopendekezwa.",
    "viewing.explainer":
        "Chagua muda unaokufaa. Wakala wako anaweza kuukubali au kupendekeza mwingine.",
    "viewing.note": "Maelezo ya kukutana (si lazima)",
    "viewing.noteHelp": "Mfano: tukutane karibu na geti kuu.",
    "viewing.send": "Tuma muda uliopendekeza",
    "viewing.futureError": "Chagua tarehe na muda wa baadaye.",
    "viewing.confirm": "Thibitisha muda",
    "viewing.cancel": "Futa miadi",
    "viewing.cancelConfirm": "Una uhakika unataka kufuta miadi hii?",
    "viewing.updated": "Miadi imebadilishwa.",
    "review.title": "Kagua upangishaji uliokamilika",
    "review.prompt": "Uzoefu wako wa kukodisha ulikuwaje?",
    "review.comment": "Maoni (si lazima)",
    "review.submit": "Tuma review iliyothibitishwa",
    "review.ratingError": "Chagua nyota 1 hadi 5.",
    "review.completedOnly":
        "Mteja mwenye ombi la KODIMALI lililokamilika pekee anaweza kutoa review.",
    "review.thanks": "Asante kwa review yako",
    "booking.status.new": "Ombi limetumwa",
    "booking.status.checking_availability": "Inaangalia upatikanaji",
    "booking.status.contacted": "Wakala amewasiliana nawe",
    "booking.status.viewing_scheduled": "Miadi imepangwa",
    "booking.status.reserved": "Imewekewa nafasi",
    "booking.status.confirmed": "Imethibitishwa",
    "booking.status.completed": "Upangishaji umekamilika",
    "booking.status.cancelled": "Imefutwa",
    "booking.status.rejected": "Imekataliwa",
    "booking.status.no_response": "Hakuna jibu",
    "booking.status.agent_delayed": "Jibu la wakala limechelewa",
    "booking.status.proposed": "Inasubiri kuthibitishwa",
    "booking.status.reschedule_requested": "Muda mwingine umeombwa",
    "booking.status.no_show": "Hakufika",
  },
};
